services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_USER=simplechurchUser
      - POSTGRES_PASSWORD=simplechurchPassword
      - POSTGRES_DB=simplechurchDb
    networks:
      - backendDb
      - dbAdminDb
    ports:
      - '5432:5432'

  dbAdmin:
    image: dpage/pgadmin4:latest
    container_name: dbAdmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "81:80"
    networks:
      - dbAdminDb

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - spring.jpa.hibernate.ddl-auto=update
      - spring.datasource.url=jdbc:postgresql://db:5432/simplechurchDb
      - spring.datasource.driverClassName=org.postgresql.Driver
      - spring.datasource.username=simplechurchUser
      - spring.datasource.password=simplechurchPassword
    ports:
      - '8081:8081'
    networks:
      - backendDb
      - backendFrontend

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    networks:
      - backendFrontend

networks:
  backendDb:
    driver: bridge
  backendFrontend:
    driver: bridge
  dbAdminDb:
    driver: bridge
