services:
  db:
    image: postgres:latest
    container_name: db
    volumes:
      - ./postgresql.conf:/etc/postgresql.conf
    environment:
      - POSTGRES_USER=simplechurchUser
      - POSTGRES_PASSWORD=simplechurchPassword
      - POSTGRES_DB=simplechurchDb
    networks:
      - backendDb
      - dbAdminDb
    ports:
      - '5432:5432'
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 800M

  dbAdmin:
    image: dpage/pgadmin4:latest
    container_name: dbAdmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "81:80"
    networks:
      - dbAdminDb
    depends_on:
      - db

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - spring.jpa.hibernate.ddl-auto=update
      - spring.datasource.url=jdbc:postgresql://db:5432/simplechurchDb
      - spring.datasource.driverClassName=org.postgresql.Driver
      - spring.datasource.username=simplechurchUser
      - spring.datasource.password=simplechurchPassword
      - spring.profiles.active=prod
    ports:
      - '8081:8081'
    networks:
      - backendDb
      - backendFrontend
    deploy:
      resources:
        limits:
          cpus: '1.8'
          memory: 3G
    depends_on:
      - db

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    networks:
      - backendFrontend
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 200M
    depends_on:
      - backend

networks:
  backendDb:
    driver: bridge
  backendFrontend:
    driver: bridge
  dbAdminDb:
    driver: bridge
