package br.com.dgc.simplechurch.member.model.enums;

public enum ReceptionMode {
    PROFESSION_OF_FAITH, PROFESSION_OF_FAITH_AND_BAPTISM, LETTER_OF_TRANSFER, JURISDICTION_ON_REQUEST,
    EX_OFFICIO_JURISDICTION, RESTORATION, APPOINTMENT_OF_PRESBYTERY
}
